---
- name: Provision Servers
  hosts: local
  connection: local
  gather_facts: False
  roles:
    - { role: server, server_name: "irc.{{ tld }}", server_region: "{{ region }}", server_image: "Fedora 20 (Heisenbug) (PVHVM)", server_domain: "{{ tld }}", server_group: irc, server_count: 1, server_auto_increment: false }
    - { role: server, server_name: "jenkins.{{ tld }}", server_region: "{{ region }}", server_image: "Fedora 20 (Heisenbug) (PVHVM)", server_domain: "{{ tld }}", server_group: jenkins, server_count: 1, server_auto_increment: false }
