---
# tasks file for roles/fail2ban
- name: Install Packages
  yum: pkg={{ item }} state={% if upgrade %}latest{% else %}present{% endif %}
  with_items:
    - whois
    - ipset
    - fail2ban

- name: Enable Fail2Ban Service
  service: name=fail2ban enabled=yes

- name: Configure Fail2Ban Service
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local owner=root group=root
  notify:
    - Restart Fail2Ban

- name: Configure SSH Filter
  template: src=filter.d/sshd.local.j2 dest=/etc/fail2ban/filter.d/sshd.local owner=root group=root
  notify:
    - Restart Fail2Ban

- name: Configure FirewallCmd IPSET Action
  template: src=action.d/firewallcmd-ipset.local.j2 dest=/etc/fail2ban/action.d/firewallcmd-ipset.local owner=root group=root
  notify:
    - Restart Fail2Ban

- name: Start Fail2Ban Service
  service: name=fail2ban state=started
