---
# tasks file for roles/logcheck
- name: Install Packages
  yum: pkg={{ item }} state={% if upgrade %}latest{% else %}present{% endif %}
  with_items:
    - logcheck

- name: Configure LogCheck
  template: src=logcheck.conf.j2 dest=/etc/logcheck/logcheck.conf owner=root group=root

- name: Add logcheck to /var/log/messages
  acl: name=/var/log/messages entity=logcheck etype=user permissions=r state=present

- name: Add logcheck to /var/log/secure
  acl: name=/var/log/secure entity=logcheck etype=user permissions=r state=present
