---
# tasks file for roles/common
- name: Check if upgraded file exists
  stat: path=/root/.ansible.znf.upgraded
  changed_when: False
  register: upgraded_file

- name: Upgrade All Packages
  yum: pkg=* state=latest
  when: not upgraded_file.stat.exists or upgrade

- name: Write upgraded file
  command: touch /root/.ansible.znf.upgraded
  when: not upgraded_file.stat.exists

- name: Install Common Packages
  dnf: pkg={{ item }} state={% if upgrade %}latest{% else %}present{% endif %}
  with_items:
    - gpg
    - htop
